#!/usr/bin/env python3
"""Render radar/SHORTLIST.md from data/verified.json (curated evidence) + data/candidates.json (live discovery).
Deadlines/days-left are recomputed at render time so the report never goes stale silently."""
import os
import re
import sys

sys.path.insert(0, os.path.dirname(__file__))
from common import ROOT, days_left, load, now_utc, parse_dt  # noqa: E402

ORDER = {"A": 0, "B": 1, "C": 2, "X": 3}


def first_iso(s):
    m = re.findall(r"\d{4}-\d{2}-\d{2}(?:T\d{2}:\d{2}(?::\d{2})?Z?)?", s or "")
    return m[-1] if m else None


def dleft(d):
    """The clock that matters: registration close if present, else the END of the build/submission window (never results date)."""
    dl = d.get("deadlines", {})
    key = next((k for k in dl if "registration" in k), None) or next((k for k in dl if k in ("build", "build_window")), None)
    iso = first_iso(dl[key]) if key else first_iso(" ".join(dl.values()))
    if not iso:
        return "?"
    x = days_left(iso if "T" in iso else iso + "T23:59:00+00:00")
    return "?" if x is None else ("CLOSED" if x < 0 else f"{x}d")


def gate_cell(g):
    return "—" if not g else f"**{g['v']}**"


def main():
    V, C = load("verified.json", {}), load("candidates.json", {})
    out = [f"# Hackathon Radar — SHORTLIST (generated {now_utc():%Y-%m-%d %H:%M} UTC)",
           "", "Generated by `radar/tools/report.py` from `radar/data/verified.json`. Do not hand-edit; edit the data.",
           "Verdicts: PASS = explicit evidence · RISK = clause exists / depends on you · UNKNOWN = not found (never PASS) · FAIL = blocking clause.", ""]
    live = [(k, v) for k, v in V.items() if v["tier"] in ("A", "B", "C")]
    live.sort(key=lambda kv: ORDER[kv[1]["tier"]])
    out += ["## Actionable board", "", "| Tier | Event | Left | Prize (as published) | Remote | Country | KYC | Payout | Paid-action | Status |", "|---|---|---|---|---|---|---|---|---|---|"]
    for k, v in live:
        g = v.get("gates", {})
        out.append(f"| {v['tier']} | [{v['name']}]({v['url']}) | {dleft(v)} | {v['prize']['text'][:60]} | {gate_cell(g.get('remote'))} | {gate_cell(g.get('country'))} | {gate_cell(g.get('kyc'))} | {gate_cell(g.get('payout'))} | {gate_cell(g.get('paid_actions'))} | {v['status']} |")
    out += ["", "## Rejected / closed (kept so we never re-research them)", "", "| Event | Why | Evidence |", "|---|---|---|"]
    for k, v in V.items():
        if v["tier"] == "X":
            why = "; ".join(f"{n}={d['v']}" for n, d in v.get("gates", {}).items()) or "see risks"
            ev = next((d["ev"] for d in v.get("gates", {}).values() if d["v"].startswith(("FAIL", "RISK"))), v["risks"][0] if v.get("risks") else "")
            out.append(f"| [{v['name'][:70]}]({v['url']}) | {v['status']} ({why}) | {ev[:220]} |")
    for k, v in live:
        out += ["", f"## {v['name']}  — tier {v['tier']} · {v['status']}", f"- Link: {v['url']}  (checked {v['checked']})",
                f"- Prize: {v['prize']['text']}", f"- Distribution: {v['prize'].get('distribution', 'UNKNOWN')}", f"- Payout: {v['prize'].get('payout', 'UNKNOWN')}"]
        if v.get("prize_evidence"):
            out.append(f"- Prize evidence: {v['prize_evidence']}")
        out.append("- Deadlines: " + "; ".join(f"{a}: {b}" for a, b in v.get("deadlines", {}).items()) + f"  → **{dleft(v)} left**")
        out.append("- Gate evidence:")
        for n, d in v.get("gates", {}).items():
            out.append(f"  - **{n} = {d['v']}** — {d['ev']}" + (f"  _(src: {d['src']})_" if d.get("src") else ""))
        for label, key in [("Judging", "judging"), ("Competition", "competition"), ("Build fit", "build_fit"), ("Reuse / X proof", "reuse")]:
            if v.get(key):
                out.append(f"- {label}: {v[key]}")
        for label, key in [("Submission requires", "submission"), ("Disqualifiers", "disqualifiers"), ("Risks", "risks"), ("Unresolved", "unresolved"), ("Next", "next")]:
            if v.get(key):
                out.append(f"- {label}:")
                out += [f"  - {x}" for x in v[key]]
    ai = [c for c in C.values() if c["platform"] == "Superteam Earn" and "ai-relevant" in c["tags"]]
    out += ["", f"## Live discovery snapshot ({len(C)} raw candidates; see data/candidates.json, data/source_health.json)"]
    out += [f"- {c['name']} — {c['prize_text']} — closes {c['deadline'][:10]} — {c['url']}" for c in ai[:10]]
    path = os.path.join(ROOT, "SHORTLIST.md")
    open(path, "w").write("\n".join(out) + "\n")
    print("wrote", path, len(out), "lines")


if __name__ == "__main__":
    main()
